import Head from "next/head";
import Image from "next/image";
import TopHeader from '../components/Header/TopHeader'
import Banner from "../components/Banner/Banner";
import styles from "../styles/Home.module.css";


import request from "../utils/request";
import ChannelSlider from '../components/ChannelSlider/ChannelSlider'






const Home = ({ actionMovies,
  comedyMovies,
  documentary,
  horrorMovies,
  netflixOriginals,
  romanceMovies,
  topRatedMovies,
  tredingMovies}) => {
  console.log(actionMovies);
  return (
    <div className="relative h-screen bg-gradient-to-b from from-gray-900/10 to-[#010511] lg:h-[140vh]">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <TopHeader />

      <main>
        {/* Banner   */}
        <Banner netflixOriginals={netflixOriginals} />

        <section>
          <ChannelSlider/>
          {/* <NetflixCarousel/> */}
          {/* Row */}
          {/* Row */}
          {/* Row */}
          {/* Row */}
          {/* Row */}
          {/* Row */}
          {/* Row */}
        </section>
      </main>
    </div>
  );
};

export default Home;

export const getServerSideProps = async () => {
  const [
    actionMovies,
    comedyMovies,
    documentary,
    horrorMovies,
    netflixOriginals,
    romanceMovies,
    topRatedMovies,
    tredingMovies,
  ] = await Promise.all([
    fetch(request.fetchNetflixOriginals).then((res) => res.json()),
    fetch(request.fetchTrending).then((res) => res.json()),
    fetch(request.fetchTopRated).then((res) => res.json()),
    fetch(request.fetchActionMovies).then((res) => res.json()),
    fetch(request.fetchComedyMovies).then((res) => res.json()),
    fetch(request.fetchHorrorMovies).then((res) => res.json()),
    fetch(request.fetchRomanceMovies).then((res) => res.json()),
    fetch(request.fetchDocumentaries).then((res) => res.json()),
  ]);

  return {
    props: {
      actionMovies:actionMovies.results,
      comedyMovies:comedyMovies.results,
      documentary:documentary.results,
      horrorMovies:horrorMovies.results,
      netflixOriginals:netflixOriginals.results,
      romanceMovies:romanceMovies.results,
      topRatedMovies:topRatedMovies.results,
      tredingMovies:tredingMovies.results,
    },
  };
};
