import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/Header/Header";
import Banner from "../components/Header/Banner";
import axios from "axios";
import request from "../utils/request";

const Home: NextPage = () => {
  return (
    <div className="relative h-screen bg-gradient-to-b from from-gray-900/10 to-[#010511] lg:h-[140vh]">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      <main>
        {/* Banner   */}
        <Banner />

        <section>
          {/* Row */}
          {/* Row */}
          {/* Row */}
          {/* Row */}
          {/* Row */}
          {/* Row */}
          {/* Row */}
        </section>
      </main>
    </div>
  );
};

export default Home;

export const getServerSideProps = async () => {
  try {
    axios
      .all([
        axios.get(request.fetchActionMovies),
        axios.get(request.fetchComedyMovies),
        axios.get(request.fetchDocumentaries),
        axios.get(request.fetchHorrorMovies),
        axios.get(request.fetchNetflixOriginals),
        axios.get(request.fetchRomanceMovies),
        axios.get(request.fetchTopRated),
        axios.get(request.fetchTrending),
      ])
      .then(
        axios.spread(
          (
            actionMovies,
            comedyMovies,
            documentary,
            horrorMovies,
            netflixOriginals,
            romanceMovies,
            topRatedMovies,
            tredingMovies
          ) => {
            console.log(actionMovies, comedyMovies);
          }
        )
      );
  } catch (error) {
    console.log("an error occured",error);
    throw new Error("failed to fetch data");
    
  }
};
